name: Job 1

on: [workflow_call]  # Este job pode ser chamado por outro workflow

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Get Random Number
        run: |
          echo "TESTE=2024" >> $GITHUB_ENV

      - name: Display Random Number
        run: |
          echo "Teste = ${{ env.TESTE }}"

