name: Job 1

on: [workflow_call]  # Este job pode ser chamado por outro workflow

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Get Random Number
        id: set-random-number
        uses: ./.github/actions/random-number-action
      - name: Display Random Number
        run: echo "Random Number ${{ steps.set-random-number.outputs.random-number }}"

