name: Job 2

on: [workflow_call]

jobs:
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Use Output from Job 1
        run: echo "Output from Job 1 ${{ needs.job1.outputs.output1 }}"
