name: Job 2

on:
  workflow_call:
    inputs:
      INPUT_TESTE:
        required: false
        type: string

jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Step without dependency
        run: echo "This step runs independently."

  job2_with_dependency:
    runs-on: ubuntu-latest
    needs: job2  # Agora esse job depende do job2
    steps:
      - name: Use Output from Job 1
        run: echo Output from Job 1 ${{ env.TESTE }}
