name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  job1:
    uses: ./.github/workflows/job1.yml@main  # Adicione a versão (branch ou tag) aqui

  job2:
    uses: ./.github/workflows/job2.yml@main  # Adicione a versão (branch ou tag) aqui
    needs: job1
