name: Main Workflow

on:
  push:
    branches:
      - master

jobs:
  job1:
    uses: ./.github/workflows/job1.yml

  job2:
    uses: ./.github/workflows/job2.yml
    with:
      INPUT_TESTE: Foi meu chapa
    needs: job1
